//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmp_Auto_Attendance
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string Name { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
