//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTimeTable
    {
        public int Id { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> SlotID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string TeacherID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Day { get; set; }
    
        public virtual AspNetRoom AspNetRoom { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
        public virtual AspNetTimeslot AspNetTimeslot { get; set; }
    }
}
