//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetLessonPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetLessonPlan()
        {
            this.AspNetLessonPlan_Topic = new HashSet<AspNetLessonPlan_Topic>();
            this.AspNetLessonPlanBreakdowns = new HashSet<AspNetLessonPlanBreakdown>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LessonPlanNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetLessonPlan_Topic> AspNetLessonPlan_Topic { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetLessonPlanBreakdown> AspNetLessonPlanBreakdowns { get; set; }
    }
}
