//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetEmployee()
        {
            this.Aspnet_Employee_Session = new HashSet<Aspnet_Employee_Session>();
            this.TeacherPenaltyRecords = new HashSet<TeacherPenaltyRecord>();
            this.EmployeeAdvanceSalaries = new HashSet<EmployeeAdvanceSalary>();
            this.AspNetEmployee_Attendance = new HashSet<AspNetEmployee_Attendance>();
            this.AspNetSalaryDetails = new HashSet<AspNetSalaryDetail>();
            this.EmployeePenalties = new HashSet<EmployeePenalty>();
            this.Employee_SalaryRecord = new HashSet<Employee_SalaryRecord>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
        }
    
        public int Id { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DateAvailable { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public string MailingAddress { get; set; }
        public string Email { get; set; }
        public string CellNo { get; set; }
        public string Landline { get; set; }
        public string SpouseName { get; set; }
        public string SpouseHighestDegree { get; set; }
        public string SpouseOccupation { get; set; }
        public string SpouseBusinessAddress { get; set; }
        public string UserId { get; set; }
        public Nullable<int> GrossSalary { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> MedicalAllowance { get; set; }
        public Nullable<int> Accomodation { get; set; }
        public Nullable<int> ProvidedFund { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> EOP { get; set; }
        public Nullable<int> Salary { get; set; }
        public string UserName { get; set; }
        public Nullable<int> VirtualRoleId { get; set; }
        public string JoiningDate { get; set; }
        public string Illness { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aspnet_Employee_Session> Aspnet_Employee_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherPenaltyRecord> TeacherPenaltyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAdvanceSalary> EmployeeAdvanceSalaries { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEmployee_Attendance> AspNetEmployee_Attendance { get; set; }
        public virtual AspNetVirtualRole AspNetVirtualRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetSalaryDetail> AspNetSalaryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePenalty> EmployeePenalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_SalaryRecord> Employee_SalaryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
    }
}
