//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTeacher
    {
        public int Id { get; set; }
        public string TeacherID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string DateAvailable { get; set; }
        public string PositionAppliedFor { get; set; }
        public string BirthDate { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public string MailingAddress { get; set; }
        public string CellNo { get; set; }
        public string Landline { get; set; }
        public string SpouseName { get; set; }
        public string SpouseHeighestDegree { get; set; }
        public string SpouseOccupation { get; set; }
        public string SpouseBusinessAddress { get; set; }
        public string DegreeCertificate { get; set; }
        public string MajorSubjects { get; set; }
        public string Year { get; set; }
        public string SchoolCollageUniversityCity { get; set; }
        public string Illness { get; set; }
    
        public virtual AspNetTeacher_Session AspNetTeacher_Session { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
