//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent_Term_Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetStudent_Term_Assessment()
        {
            this.AspNetStudent_Term_Assessments_Answers = new HashSet<AspNetStudent_Term_Assessments_Answers>();
        }
    
        public int Id { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string TeacherComments { get; set; }
        public string PrincipalComments { get; set; }
        public string ParentsComments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> NotifyTeacher { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
        public virtual AspNetTerm AspNetTerm { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Term_Assessments_Answers> AspNetStudent_Term_Assessments_Answers { get; set; }
    }
}
