//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetMessage_Receiver
    {
        public int Id { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string ReceiverID { get; set; }
        public string Seen { get; set; }
        public System.DateTime SeenTime { get; set; }
    
        public virtual AspNetMessage AspNetMessage { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
