//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPushNotification
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> IsOpenStudent { get; set; }
        public Nullable<bool> IsOpenParent { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
