//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetStudent()
        {
            this.AspNetStudent_Session_class = new HashSet<AspNetStudent_Session_class>();
            this.NonRecurringFeeMultipliers = new HashSet<NonRecurringFeeMultiplier>();
            this.StudentChallanForms = new HashSet<StudentChallanForm>();
            this.StudentDiscounts = new HashSet<StudentDiscount>();
            this.StudentFeeMonths = new HashSet<StudentFeeMonth>();
            this.StudentPenalties = new HashSet<StudentPenalty>();
        }
    
        public int Id { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Level { get; set; }
        public string SchoolName { get; set; }
        public string BirthDate { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Session_class> AspNetStudent_Session_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonRecurringFeeMultiplier> NonRecurringFeeMultipliers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChallanForm> StudentChallanForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDiscount> StudentDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeeMonth> StudentFeeMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPenalty> StudentPenalties { get; set; }
    }
}
