//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent_PaymentDetail
    {
        public int Id { get; set; }
        public Nullable<int> Student_PaymentID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> PreviousFeeID { get; set; }
    
        public virtual AspNetFinanceLedger AspNetFinanceLedger { get; set; }
        public virtual AspNetStudent_Payment AspNetStudent_Payment { get; set; }
        public virtual AspNetStudent_Payment AspNetStudent_Payment1 { get; set; }
    }
}
