//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetAnnouncement_Subject
    {
        public int Id { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
    
        public virtual AspNetAnnouncement AspNetAnnouncement { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
    }
}
