//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetSession()
        {
            this.Aspnet_Employee_Session = new HashSet<Aspnet_Employee_Session>();
            this.AspNetAbsent_Student = new HashSet<AspNetAbsent_Student>();
            this.AspNetAnnouncements = new HashSet<AspNetAnnouncement>();
            this.AspNetAssessments = new HashSet<AspNetAssessment>();
            this.AspNetAssessment_Question = new HashSet<AspNetAssessment_Question>();
            this.AspNetClasses = new HashSet<AspNetClass>();
            this.AspNetEmp_Auto_Absent = new HashSet<AspNetEmp_Auto_Absent>();
            this.AspNetFeedBackForms = new HashSet<AspNetFeedBackForm>();
            this.AspNetFinanceLedgers = new HashSet<AspNetFinanceLedger>();
            this.AspNetHoliday_Calendar_Notification = new HashSet<AspNetHoliday_Calendar_Notification>();
            this.AspNetMessages = new HashSet<AspNetMessage>();
            this.AspNetNotifications = new HashSet<AspNetNotification>();
            this.AspNetParent_Session = new HashSet<AspNetParent_Session>();
            this.AspNetParentTeacherMeetings = new HashSet<AspNetParentTeacherMeeting>();
            this.AspNetPushNotifications = new HashSet<AspNetPushNotification>();
            this.AspNetSalaries = new HashSet<AspNetSalary>();
            this.AspNetStudent_AutoAttendance = new HashSet<AspNetStudent_AutoAttendance>();
            this.AspNetStudent_Fine = new HashSet<AspNetStudent_Fine>();
            this.AspNetStudent_Notification = new HashSet<AspNetStudent_Notification>();
            this.AspNetStudent_Session_class = new HashSet<AspNetStudent_Session_class>();
            this.AspNetStudent_Term_Assessment = new HashSet<AspNetStudent_Term_Assessment>();
            this.AspNetTeacher_Session = new HashSet<AspNetTeacher_Session>();
            this.AspNetTerms = new HashSet<AspNetTerm>();
            this.AspNetUsers_Session = new HashSet<AspNetUsers_Session>();
            this.Events = new HashSet<Event>();
            this.Ledgers = new HashSet<Ledger>();
            this.NonRecurringFeeMultipliers = new HashSet<NonRecurringFeeMultiplier>();
            this.StudentRecurringFees = new HashSet<StudentRecurringFee>();
            this.ruffdatas = new HashSet<ruffdata>();
            this.StudentFeeMonths = new HashSet<StudentFeeMonth>();
            this.TeacherPenaltyRecords = new HashSet<TeacherPenaltyRecord>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int Id { get; set; }
        public string SessionName { get; set; }
        public Nullable<System.DateTime> SessionStartDate { get; set; }
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aspnet_Employee_Session> Aspnet_Employee_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAbsent_Student> AspNetAbsent_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAnnouncement> AspNetAnnouncements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAssessment> AspNetAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAssessment_Question> AspNetAssessment_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetClass> AspNetClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEmp_Auto_Absent> AspNetEmp_Auto_Absent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetFeedBackForm> AspNetFeedBackForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetFinanceLedger> AspNetFinanceLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetHoliday_Calendar_Notification> AspNetHoliday_Calendar_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetMessage> AspNetMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetNotification> AspNetNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetParent_Session> AspNetParent_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetParentTeacherMeeting> AspNetParentTeacherMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetPushNotification> AspNetPushNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetSalary> AspNetSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_AutoAttendance> AspNetStudent_AutoAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Fine> AspNetStudent_Fine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Notification> AspNetStudent_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Session_class> AspNetStudent_Session_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Term_Assessment> AspNetStudent_Term_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Session> AspNetTeacher_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTerm> AspNetTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers_Session> AspNetUsers_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ledger> Ledgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonRecurringFeeMultiplier> NonRecurringFeeMultipliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRecurringFee> StudentRecurringFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruffdata> ruffdatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeeMonth> StudentFeeMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherPenaltyRecord> TeacherPenaltyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
