//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetClass_FeeType
    {
        public int Id { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Type { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetFinanceLedger AspNetFinanceLedger { get; set; }
    }
}
