//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetHomework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetHomework()
        {
            this.AspNetStudent_HomeWork = new HashSet<AspNetStudent_HomeWork>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PrincipalApproved_status { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_HomeWork> AspNetStudent_HomeWork { get; set; }
    }
}
