//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent_HomeWork
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> HomeworkID { get; set; }
        public string Reading { get; set; }
        public string TeacherComments { get; set; }
        public string ParentComments { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetHomework AspNetHomework { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
