//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePenalty
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PenaltyId { get; set; }
        public string Month { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual AspNetEmployee AspNetEmployee { get; set; }
        public virtual EmployeePenaltyType EmployeePenaltyType { get; set; }
    }
}
