//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_SalaryIncrement
    {
        public int Id { get; set; }
        public Nullable<double> PreviousSalary { get; set; }
        public Nullable<double> AfterSalary { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> EmpSalaryRecordId { get; set; }
        public Nullable<double> IncrementAmount { get; set; }
    
        public virtual Employee_SalaryRecord Employee_SalaryRecord { get; set; }
    }
}
