//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ledger()
        {
            this.VoucherRecords = new HashSet<VoucherRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> StartingBalance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> LedgerGroupId { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public Nullable<int> LedgerHeadId { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual LedgerGroup LedgerGroup { get; set; }
        public virtual LedgerHead LedgerHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherRecord> VoucherRecords { get; set; }
    }
}
