//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month_Multiplier
    {
        public int Id { get; set; }
        public string AdjustedMonth { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> FeeMonthId { get; set; }
        public string PaymentMonth { get; set; }
    
        public virtual StudentFeeMonth StudentFeeMonth { get; set; }
    }
}
