//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruffdata
    {
        public int id { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string FatherUserName { get; set; }
        public string FatherPassword { get; set; }
        public string StudentUserName { get; set; }
        public string StudentPassword { get; set; }
        public string StudentClassName { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
    }
}
