//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeMonth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentFeeMonth()
        {
            this.Month_Multiplier = new HashSet<Month_Multiplier>();
            this.StudentChallanForms = new HashSet<StudentChallanForm>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Months { get; set; }
        public string Status { get; set; }
        public Nullable<double> InstalmentAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> Multiplier { get; set; }
        public Nullable<double> FeePayable { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<System.DateTime> ValildityDate { get; set; }
        public string FeeType { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalFee { get; set; }
        public Nullable<double> FeeReceived { get; set; }
        public Nullable<double> NotesFee { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual AspNetStudent AspNetStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Month_Multiplier> Month_Multiplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChallanForm> StudentChallanForms { get; set; }
    }
}
