//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRecurringFee
    {
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<double> ComputerLabCharges { get; set; }
        public Nullable<double> SecurityServices { get; set; }
        public Nullable<double> LabCharges { get; set; }
        public Nullable<double> Transportation { get; set; }
        public Nullable<double> SportsShirt { get; set; }
        public Nullable<double> ChineseClassFee { get; set; }
        public Nullable<double> AdvanceTax { get; set; }
        public Nullable<double> Other { get; set; }
        public Nullable<double> TutionFee { get; set; }
        public Nullable<double> TotalFee { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
    }
}
