//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherRecord
    {
        public int Id { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> AfterBalance { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string Description { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
